settings:
  title: 'Superhub Status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: frame_4.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All goood'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: superhub-host # unique identifier
    name: superhub.host
    description: 'Main site' # default=empty
    url: 'https://superhub.host/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: panel-superhub-host
    name: panel.superhub.host
    description: 'Superhub panel'
    url: 'https://panel.superhub.host'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: feedback-superhub-host
    name: feedback.superhub.host
    description: 'Superhub feedback'
    url: 'https://feedback.superhub.host/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: cdn-superhub-host
    name: cdn.superhub.host
    description: 'Superhub cdn for images on site'
    url: 'https://cdn.hosting.superhub.xyz/images/seo/background_seo.png'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: siren-mcs
    name: siren.mcs-1
    description: 'MSK-M1 node'
    url: 'https://siren.mcs.s-hub.xyz:8086'
    method: GET
    expectStatus: 401
    followRedirect: true
